id: IBE3015C4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T18:21:55+00:00'
last_modified: '2022-06-08T05:55:52.489321+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25509
  title: རྩིས་འཁོར་ཤེས་བྱ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    B88C:
      image_group_id: I1KG25511
      title: ''
      total_pages: 206
      order: 1
      base_file: B88C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
